# Generated by Django 3.2.8 on 2021-10-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
