# Generated by Django 3.2.8 on 2021-10-08 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='price',
        ),
    ]
